### ISSUE TITLE
这个软件界面不能缩小吗

### ISSUE THREAD

**Issue by marigold233** [rujax/reminder#1]
![image](https://github.com/rujax/reminder/assets/62014410/9cc6da79-0ad8-49ea-9dd5-51cbe160d73e)

**Comment by rujax** [comment]
多谢反馈，后续版本会添加一下处理。
方便的话，麻烦提供一下桌面分辨率吧。
目前的版本是基于 **1080P** 的，之前没有考虑到更小分辨率的情况。

**Comment by marigold233** [comment]
> 多谢反馈，后续版本会添加一下处理。 方便的话，麻烦提供一下桌面分辨率吧。 目前的版本是基于 **1080P** 的，之前没有考虑到更小分辨率的情况。

你看看
![image](https://github.com/rujax/reminder/assets/62014410/1c6a8d7b-388c-41e3-a274-a9984f11f965)

**Comment by rujax** [comment]
> > 多谢反馈，后续版本会添加一下处理。 方便的话，麻烦提供一下桌面分辨率吧。 目前的版本是基于 **1080P** 的，之前没有考虑到更小分辨率的情况。
> 
> 你看看 ![image](https://user-images.githubusercontent.com/62014410/252139131-1c6a8d7b-388c-41e3-a274-a9984f11f965.png)

应该是 125% 这个缩放有影响 我考虑一下解决方案

**Comment by rujax** [comment]
试一下最新的 `0.2.0` 版本吧。应该（可能）可以解决你的问题。
